<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_undefined undefined_fa fa-edit</name>
   <tag></tag>
   <elementGuidId>6286ba5b-f166-4a27-84ee-b522501c057e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>100b185b-2882-4b33-9c79-d6b2b2a1af67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>f37321f4-019c-440c-a41b-2b626b95c976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;hold-transition skin-blue sidebar-mini&quot;]/app-root[1]/app-admin[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/app-training-scheduling-create[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]/span[1]/div[@class=&quot;col-md-12 col-lg-6&quot;]/fieldset[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ng-star-inserted&quot;]/table[@class=&quot;row-border hover table table-striped&quot;]/thead[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[3]/div[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-xs-3&quot;]/span[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;btn btn-primary btn-xs&quot;]/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>70049324-137f-4651-9430-f2e0711fb714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>4f5482b8-09b6-4815-bafb-52cb41046caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
