<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Bibungo  Bwiza  Kagasa  Gateko  Nyab_b1236b</name>
   <tag></tag>
   <elementGuidId>39ca1098-eb2b-4443-b8e8-6ab9d4aea4a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='location-village']/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>70a48c85-5913-442b-b110-6ed0c8c9ccf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>village_id</value>
      <webElementGuid>26cb89c4-56b9-437f-b473-f5bed23e49f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6b1dd3cc-3bc1-476e-bc10-97f0185c8b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bibungo  Bwiza  Kagasa  Gateko  Nyabihu  Rutagara I  Ruyenzi  Rutagara Ii </value>
      <webElementGuid>1087f160-917b-47ab-935b-20faa62bbb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;hold-transition skin-blue sidebar-mini&quot;]/app-root[1]/app-admin[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/app-training-scheduling-create[1]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]/span[1]/div[@class=&quot;col-sm-12 ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;location-village&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>a8d7ad68-3571-4ea7-a020-06593cb7e142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location-village']/div/select</value>
      <webElementGuid>cc839a52-fc0a-40c8-b74d-a791d1cb3c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Village'])[1]/following::select[1]</value>
      <webElementGuid>1f65343d-92d8-4be8-b056-3eb8b2fae1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cell'])[1]/following::select[2]</value>
      <webElementGuid>9bf37ce7-d081-4723-966e-d15e51a0802b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venue'])[1]/preceding::select[1]</value>
      <webElementGuid>2644ba28-e1fc-4354-9e74-8b3d51128d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starting Date and Time of the training'])[1]/preceding::select[1]</value>
      <webElementGuid>1755b7f9-12c9-4ef4-b9b8-804a7ca90680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>3ac240d8-0098-48e2-863b-5a048408a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' Bibungo  Bwiza  Kagasa  Gateko  Nyabihu  Rutagara I  Ruyenzi  Rutagara Ii ' or . = ' Bibungo  Bwiza  Kagasa  Gateko  Nyabihu  Rutagara I  Ruyenzi  Rutagara Ii ')]</value>
      <webElementGuid>105fa450-4b80-4b37-9efc-d4a63fb3161b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
